i13: Implement SMC^2
mrc-ide/mcstate pull request #77
Opened 2020-10-01 19:44 UTC by richfitz

This might be broken into two at around e46861f to split into support/implementation

Fixes #13

2020-12-01 10:18 UTC, richfitz commented
For debugging:

```
dat <- example_sir()
f <- particle_filter$new(dat$data, dat$model, 42, dat$compare,
                         index = dat$index)
p <- smc2_parameters$new(
  list(
    smc2_parameter("beta",
                   function(n) runif(n, 0, 1),
                   function(x) dunif(x, 0, 1, log = TRUE),
                   min = 0, max = 1),
    smc2_parameter("gamma",
                   function(n) runif(n, 0, 1),
                   function(x) dunif(x, 0, 1, log = TRUE),
                   min = 0, max = 1)))

## This runs fairly well, up to the point where we fail to compute the
## vcv, which fails because we've set the state to be NULL somehow.
set.seed(1)
e <- smc2_engine$new(p, f, 100)
e$run()
```

2021-02-04 17:58 UTC, johnlees commented
At the end of the test above, I tried the following to sample parameters from the posterior:
```
w <- scale_log_weights(e$.__enclos_env__$private$state$log_posterior)$weights/sum(scale_log_weights(e$.__enclos_env__$private$state$log_posterior)$weights)
s = sample(seq_len(100), prob = w, replace = TRUE)
plot(e$.__enclos_env__$private$state$pars[s, ])
```

(obviously shouldn't be accessing the private members, but will add this to the object if it's correct)

2021-02-05 12:00 UTC, johnlees requested changes
I had a bit of a play around with this, varying number of parameter sets and priors on the parameters. Looks like the results are sensible to me, but would probably benefit from more testing too

Code is great, and makes sense to merge this now, and note what we might want to add in the future as issues

2021-02-05 12:27 UTC, richfitz commented on tests/testthat/test-smc2.R
> +  n_parameter_sets <- 20
With those it's fast enough for the test. It might make more sense to truncate in the example though

2021-02-05 12:33 UTC, johnlees commented on R/smc2.R
> +      private$ess[private$step_current] <- ess
```suggestion
      ess <- sum(private$state$weights)^2 / sum(private$state$weights^2)
      private$step_current <- private$step_current + 1L
      private$ess[private$step_current] <- ess
      private$evidence[private$evidence] <- private$state$weights * private$state$log_likelihood / sum(private$state$weights)
```

2021-02-05 12:34 UTC, johnlees commented on R/smc2.R
> +      private$ess <- rep(NA_real_, private$n_steps)
```suggestion
      private$ess <- rep(NA_real_, private$n_steps)
      private$evidence <- rep(NA_real_, private$n_steps)
```

2021-02-05 12:34 UTC, johnlees commented on R/smc2.R
> +    ess = NULL,
```suggestion
    ess = NULL,
    evidence = NULL,
```

2021-02-22 12:44 UTC, richfitz commented on R/smc2.R
> +##' Run a SMC^2. This is experimental and subject to change. Use at
done in c2fd150

2021-02-22 12:45 UTC, richfitz commented on R/smc2.R
> +    initialize = function(pars, filter, control) {
Definitely not straightforward, definitely needed. Logged an empty issue here: https://github.com/mrc-ide/mcstate/issues/112

2021-02-22 12:47 UTC, richfitz commented on R/smc2.R
> +##' @export
yup, done

2021-02-22 13:30 UTC, richfitz commented
Relevant diff since last review: https://github.com/mrc-ide/mcstate/compare/cb6e8bb...13-smc2

2021-02-22 13:32 UTC, johnlees approved these changes

2021-02-22 13:32 UTC, merged